### PR TITLE
example solution for duplicate filenames

### PR DESCRIPTION
**Pull request by phryneas**
This provides an example solution for #53 - the problem that multiple packages with the same name, but different maintainer/namespace, can overwrite each other. (like `redux` and `@types/redux`)

The downside is: this changes the expected format of file names in `yarn.nix`, so I believe all currently existsing `yarn.nix` in nixpkgs will fail if this is applied.

I know that this is no final solution, and you should not merge this, but I guess #53 is not the place for further discussion (I guess I caused enough notification emails over there ;) ), and maybe one of the people who had the problem initially want a quick fix, so they can try this branch.

Meanwhile, we can try to find a better solution - but I can't really think of something generic that would not require a change for the current file format.

### CODE REVIEW

**Comment by zimbatm** [comment]
Thanks, that looks pretty good already. Is there any scenario where the domain would be different than `registry.yarnpkg.com`?

If you could add a testcase that demonstrates the name clashing to the PR it would be super helpful.

**Comment by phryneas** [comment]
An example reproduction testcase would be:

package.json
```
{
  "name": "duplicate-pkgs",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@types/minimist": "^1.2.0",
    "minimist": "^1.2.0"
  }
}
```

yarn.lock
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@types/minimist@^1.2.0":
  version "1.2.0"
  resolved "https://registry.yarnpkg.com/@types/minimist/-/minimist-1.2.0.tgz#69a23a3ad29caf0097f06eda59b361ee2f0639f6"

minimist@^1.2.0:
  version "1.2.0"
  resolved "http://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz#a35008b20f41383eec1fb914f4cd5df79a264284"
```

(the error occurs only when both packages are at exact the same version, which many @types are not!)

I tried writing a test like
```
{
  duplicate-pkgs = 
    let 
      test = ((import (yarn2nix.mkYarnNix ./duplicate-pkgs/yarn.lock)) { linkFarm="dummy"; fetchurl="dummy"; }).packages; 
    in 
      assert (length test) == 2; "succeeded";
}
```

but obviously I'm doing something wrong there. Do you have any idea on how to test that?


Oh, and for the registry.yarnpkg.com part: I believe there will be urls from other domains.  But in the case of foo.bar, the derivation name would be prepended with `https---foo-bar-` which is a bit ugly but should work nonetheless.

**Comment by phryneas** [comment]
I finally found the time to add a working test.

**Comment by zimbatm** [comment]
nice. I don't have a better idea so let's merge this

**Comment by phryneas** [comment]
@zimbatm cool :)
Do you know how the current state of yarn2nix is? Is it currently stable enough to release a new version and get that up into nixpkgs? Then I could package Oni and maybe a native build of VSCode.

**Comment by zimbatm** [comment]
It probably needs to be tested a bit more, the workspaces addition have been creating a lot of changes.

Unfortunately yarn2nix can't be used by other packages in nixpkgs due to the Import From Derivation

**Comment by phryneas** [comment]
Could you explain that "Import From Derivation"? Yarn2nix is part of nixpkgs, so it should be possible to call it from another derivation or am I missing something?

**Comment by zimbatm** [comment]
Import From Derivation (IFD) is what happens when the `import` keyword is loading the result of a derivation. Eg:
```nix
let
  myDrv = runCommand "foo.nix" "echo {a=3;} > $out";
in
  (import myDrv).a # => 3
```
yarn2Nix uses this to generate the yarn.nix file if it's not provided. It also loads the `package.json` that come from the `src` (which is usually a derivation as well) to set a default name and version.

**Comment by phryneas** [comment]
Okay, I'm feeling a bit dumb here, but I'm still not getting why that wouldn't work in nixpkgs. 
Is this some hydra speciality or something with how nixpkgs are built?

Also, as you describe that this is required for the yarn.nix: could this be worked around by including a pre-built yarn.nix, just like yarn2nix does itself?

**Comment by moretea** [comment]
IFD is a option that can be disabled on Hydra, and the Hydra for the NixOS infrastructure has disabled this.

I don't know if this is currently the case, but this was definitely my initial intention when I started yarn2nix to not have to rely on IFD if you specify a `yarn.nix` file. The automatically generated yarn2nix is a nice convenience feature for people to not have to create and include a extra .nix file in their repositories, and can have IFD enabled.

You can verfiy if this it is actually needed by running:
```
nix-build --option allow-import-from-derivation=false $YOUR_NIX_FILE
```
You can learn more about these options via `man nix.conf`. (I didn't verify that this is the exact correct invocation, please complain if this is wrong ;))

**Comment by phryneas** [comment]
Thanks, I'll look into that :)

**Comment by zimbatm** [comment]
Eg: `nix-build --option allow-import-from-derivation false tests.nix -A duplicate-pkgs`

**Comment by zimbatm** [comment]
for the yarn.nix is can be generated and then added to the derivation:
```
mkYarnPackage {
  yarnNix = ./yarn.nix;
}
```
For the package.json it's harder, it read for the workspaces feature as well now.

**Comment by shmish111** [comment]
@phryneas I don't understand how to use `offline_cache` since this change, all the names are wrong?

**Comment by phryneas** [comment]
@shmish111 did you re-create the yarn.nix after updaing yarn2nix? This changes the file format so old yarn.nix might not be compatible.

**Comment by shmish111** [comment]
yeah, the issue is that the link farm that is created has names such as `spago___spago_0.7.7.tgz` which presumably is not possible for yarn to understand, I think it would expect something like `spago-0.7.7.tgz` although I'm not sure. The end result is
```
[2/4] Fetching packages...
error Can't make a request in offline mode ("https://registry.yarnpkg.com/spago/-/spago-0.7.7.tgz")
```
during my nix build.

The code I'm using here is
```
  configurePhase = ''
    export HOME="$NIX_BUILD_TOP"
    yarn --offline config set yarn-offline-mirror ${yarnDeps.offline_cache}
    yarn --offline config set yarn-offline-mirror-pruning true
    yarn --offline install
''
```

**Comment by phryneas** [comment]
Sorry, you are using this in a way which I myself never have used nor really know anything about. Maybe pinging one of the package maintainers themselves about this might be a better idea. @moretea @zimbatm

**Comment by shmish111** [comment]
Yeah, I have another issue open. I don't understand though, how _do_ you use this? Since the names are not the same as those inside the package.json that each package has within itself, how do you actually use these derivations?

**Comment by shmish111** [comment]
@phryneas and anyone reading, I worked it out. I looked a bit deeper into `mkYarnPackage` and saw that everything is done in the `configurePhase` which I was overriding. I moved my stuff into the `buildPhase` and apart from a few paths needing juggling around it all worked.

**Comment by shmish111** [comment]
@phryneas I came back to this recently as during an upgrade we actually came across the bug you fixed here. I was actually using an older version of yarn2nix without your fix so I upgraded and came back to the same issue. The offline cache that nix generates has names prefixed by the namespace etc and so it seems to be in a format that yarn can't recognize at all. I can't see if this is supposed to be fixed somewhere before the offline cache is generated but in my case it isn't.

I am just using `yarn2nix` to generate `yarn.nix` offline and then `yarn2nix.mkYarnPackage` during the pure build of my project. The pure build fails because yarn can't find anything in the offline cache.

**Comment by phryneas** [comment]
@shmish111 Sorry, but it's more than a year ago, and I haven't really used yarn2nix since. I fear you'll have to do some digging on your own :(

**Pull request merged**
