### PR TITLE
support git dependencies on hydra (fixes #99)

### LINKED ISSUE #99: builtins.fetchGit doesn't work on Hydra
Hi everyone, I found the following problem: As long as you add package.json and yarn.nix to nixpkgs, Hydra can use yarn2nix just fine, _unless_ there are git dependencies:
https://gist.github.com/GrahamcOfBorg/c37158bafe920d55754e49540461116b

I would suggest to add a mode where git hashes are added when generating yarn.nix and pkgs.fetchgit is used instead of pkgs.fetchGit. Since yarn.nix has to be added to nixpkgs anyways to prevent IFD issues on Hydra, this is only a small inconvenience.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by globin** [comment]
Should we maybe just use this by default?

**Comment by ghost** [comment]
> Should we maybe just use this by default?

I probably could have documented a bit better why I did it this way.
Enabling this will break builds for packages with git dependencies that don't ship yarn.nix, because it requires a network connection to get the hash sum.

Maybe we can make it the default value and pass "--no-hydra" (or similar) when yarn2nix is called at build time to generate yarn.nix on-the-fly.

**Comment by ghost** [comment]
> Should we maybe just use this by default?

I now changed it to use pkgs.fetchgit as default and provide a parameter to use builtin fetchGit, which is always passed when generating yarn.nix on the fly.

**Comment by ghost** [comment]
@zimbatm can you give a review and possibly merge?

**Review by globin — APPROVED** [review]

**Comment by zimbatm** [comment]
thanks!

**Pull request merged**
