### PR TITLE
Add test based on Daedalus (see #49)

### PR DESCRIPTION
**Pull request by jluttine**
This test fails:

```
$ nix-build
these derivations will be built:
  /nix/store/zr8jjx7kik8sxd3y492hls04n7zyzc39-daedalus-modules-0.8.0.drv
  /nix/store/jsk1gwd3h5s4qqhrcr9gf7kp914f6r7p-weave-front-end.drv
building path(s) ‘/nix/store/4vndvpdq4rdjlmkxm4v1nsbg4bhcs1w9-daedalus-modules-0.8.0’
configuring
building
yarn config v1.3.2
warning package.json: No license field
success Set "yarn-offline-mirror" to "/nix/store/j0fawvns8n0s89qfv6jjakdafjivnbcw-offline".
Done in 0.04s.
yarn install v1.3.2
warning package.json: No license field
warning daedalus@0.8.0: No license field
[1/4] Resolving packages...
error Couldn't find any versions for "aes-js" that matches "2.1.1" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
builder for ‘/nix/store/zr8jjx7kik8sxd3y492hls04n7zyzc39-daedalus-modules-0.8.0.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/jsk1gwd3h5s4qqhrcr9gf7kp914f6r7p-weave-front-end.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/jsk1gwd3h5s4qqhrcr9gf7kp914f6r7p-weave-front-end.drv’ failed
```

### CODE REVIEW

**Comment by zimbatm** [comment]
@jluttine what version of yarn are you using? I had to re-run yarn (1.3.2) on this package because it was complaining that the yarn.lock file needed some changes.

**Comment by jluttine** [comment]
@zimbatm 
```
$ yarn -v
1.3.2
```

**Comment by jluttine** [comment]
I didn't generate the lock file myself. I just used what was in the Daedalus repo and removed most of the content to make it simple.

**Comment by jluttine** [comment]
I'm not familiar with yarn at all so I might be doing something wrong.

**Comment by zimbatm** [comment]
it looks like the yarn.lock version bounds have changed. even running yarn on daedalus itself has the same  problem.

**Comment by jluttine** [comment]
Ok. Not sure I fully understand the issue. So is the problem any of these:
- yarn.lock is not in sync with package.json and should be re-generated with yarn
- yarn.lock has been generated with old yarn and should be re-generated with newer yarn
- yarn has a bug

Or something else?

**Comment by zimbatm** [comment]
I would recommend upgrading yarn to the latest version and update the daedalus repo's yarn.lock with it for a start. That should fix the aes-js issue.

**Comment by zimbatm** [comment]
the project is not straight-forward to package because of dependencies on electron. You are probably going to need to inject the node headers for gyp to function properly.

**Comment by domenkozar** [comment]
See https://github.com/input-output-hk/daedalus/pull/790

**Comment by moretea** [comment]
This appears to be solved/not relevant anymore. Please re-open if this is not the case.

**Pull request closed without merging**
