### PR TITLE
Populate meta automatically

### PR DESCRIPTION
**Pull request by nicknovitski**
I'm not sure if you had a different approach in mind, but I thought this would be an improvement.

I would have inherited the platforms attribute from yarn, but surprisingly it doesn't have one.

### CODE REVIEW

**Comment by zimbatm** [comment]
Yes that's good. There are a few more things that could be done if you are up for it like adding meta.version and mapping the packageJSON license to lib.licenses for meta.license.

**Comment by nicknovitski** [comment]
Ooh, interesting.  Yeah, I'll try my hand at those.

**Comment by nicknovitski** [comment]
Having looked into it further, I hope you'll forgive me for not trying to add full SPDX expression parsing in this PR, but the simple case of turning a string which is probably an spdxID into a set which is either from `lib.licenses` or similar to them in structure is should be very possible.

**Comment by nicknovitski** [comment]
```
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to registry.yarnpkg.com:443 
error: cannot download uglify-js-2.7.5.tgz from any mirror
```
 😞

**Comment by zimbatm** [comment]
looks like a transient error

**Pull request merged**
