### PR TITLE
Adds support for org names in package.json

### PR DESCRIPTION
**Pull request by johnchildren**
This commit adds a function to reformat the string in the name field of
a package.json into a format that nix can use as a derivation name. This
is done through a combination of nix builtins that may not be ideal.

This is necessary because the organization in npm scoping is incompatible with
the format for nix package names.

---
I don't think this is incompatible with https://github.com/moretea/yarn2nix/pull/23 as this addresses a slightly different issue, for when the "root" `package.json` contains a scoped name.

I am also very unsure if this is the best way to do this as it does seem very hacky so would greatly appreciate feedback!

### CODE REVIEW

**Comment by johnchildren** [comment]
This should actually be reasonably trivial to add tests for, so will also do that!

edit: or at least it would be if I could find a popular open source project that has an organization name and a `yarn.lock`.

**Comment by zimbatm** [comment]
Sounds good to me.

Do you mind adding a test case for it?

**Comment by johnchildren** [comment]
Finding a real `package.json` that was published by an organization, was open source, had a yarn.lock and had a name field set was surprisingly difficult, but the test seems to work at least. Hope this is satisfactory, otherwise I can try and find another!

**Comment by zimbatm** [comment]
perfect, thanks!

**Pull request merged**
