### PR TITLE
Yarn.lock argument

### PR DESCRIPTION
**Pull request by zimbatm**
Hey,

this isn't working for my package yet but I wanted to get the idea across.

In my ideal world, developers can just install yarn and not be forced to use nix (yet) to update the package.nix in sync.

### CODE REVIEW

**Comment by moretea** [comment]
I thought about doing something similar to this, but thought that this would require an impure function. But I guess that you're quite right, and that this should work as well.

**Comment by zimbatm** [comment]
@moretea the PR has expanded a bit in scope but doesn't change the project fundamentally. Do you mind merging the existing changes?

**Comment by zimbatm** [comment]
I have a second branch where I tried moving the unpack phase into nix but that didn't go well because yarn does more than just unpacking.

**Comment by moretea** [comment]
Done! We could/should talk a bit at FOSDEM about how we should continue with this. I won't have time to work on this this week unfortunately

**Pull request merged**
