### PR TITLE
Initial work to support git and namespaces

### PR DESCRIPTION
**Pull request by coltfred**
This is still kind of broken, but my nix fu is failing me (because I have little).

1) This PR attempts to deal with namespacing (I see there is different PR open #22 for it, but I don't think it'll work). The name needs to be unique, which means we need to keep the namespacing (I think). So I stripped the `@` and replaced `/` with `_` since `@` and `/` are not legal in nix

2) I added functionality to support *getting* the deps with nix. This appears to work really well.

3) The "found" used to be based on name, but I think it might be safer to use the URL where the package comes from because there isn't a great concept of "name" with git in the mix.

I'd love to hear any comments. Building the test project worked fine still. Could someone with more experience give it a test drive?

### CODE REVIEW

**Comment by moretea** [comment]
This looks awesome! I'm on a short holiday trip to Berlin the next few days. Maybe @zimbatim can have a look? Otherwise I'll try to get back to this at the end of this week

**Comment by coltfred** [comment]
@moretea No huge hurry, I'd just love to make sure this is the right thing to do and learn more about Nix as I go. Since the @ tagging above didn't seem to work, I'll tag @zimbatm

**Review by zimbatm — COMMENTED** [review]
nice!

does fetchgit work without providing the sha as well?

**Comment by coltfred** [comment]
@zimbatm It appears to, though I am having a problem with a build that *has* a git dependency. 

`nix-build` errors with the following.

```
yarn config v0.22.0
success Set "yarn-offline-mirror" to "/nix/store/xdbj7f984dsr3xrvxqiqp8bc4cwbz4f2-offline".
Done in 0.06s.
yarn install v0.22.0
[1/4] Resolving packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
builder for ‘/nix/store/yb5gwnpx9y2y0lpppcyib472yynq3kph-XXXXXXXX-modules.drv’ failed with exit code 1
```

This is after the fetchgit is successful.

I'm not sure if this is a problem with my repo build (for nix) or a different problem... I'd be grateful for someone to take a look on a build that they know the `default.nix` definition for.

**Comment by zimbatm** [comment]
@coltfred it looks like yarn is trying to use the git binary. Did you add git as part of the buildInputs? Another reason might be that yarn is trying to clone the git repo again.

**Comment by coltfred** [comment]
@zimbatm I think yarn is trying to fire up git. I tried to add <git> to the imports, but I'm honestly just grasping at straws. The repo I'm working with I can't open up, and I'm crazy busy for the next week so any help would be appreciated.

**Comment by rimmington** [comment]
The issue here is that the `sed` command in `buildYarnPackageDeps` only re-writes `resolved` lines in `yarn.lock` that start with `https`. Unfortunately, after manually editing `yarn.lock` to do this myself, I ran into a number of other issues:

1. The `fetchgit` result is a directory, and yarn expects a tarball.
2. I modified `yarn.nix` to create a tarball using `npm pack` (to get the `package/` structure in the other tarballs), but yarn complained that the tarball was invalid. Repacking the result with GNU tar got rid of this error, but then I ran into
3. `error Couldn't find a package.json file in "/tmp/nix-build-my-package.drv-7/yarn_home/.cache/yarn/my-package-dep-1.0.0-d725ebca1e1873b134f0fcec0b0e9a8b194dda3d"`. I'm still not sure what's going on here, but yarn isn't unpacking the tarball into it's cache, because that `my-package-dep...` directory doesn't exist. There are a number of open yarn issues related to Git deps and the offline cache: https://github.com/yarnpkg/yarn/issues/2333, https://github.com/yarnpkg/yarn/pull/2806, https://github.com/yarnpkg/yarn/issues/3154.

Something else to note: using `fetchgit` without a hash produces a result that isn't the same as running `nix-prefetch-git`, which will cause sadness for how my org is dealing with private Git dependencies. That's something I think can be addressed separately though, and having an offline, deterministic `yarn.lock` -> `yarn.nix` is really valuable.

**Comment by manveru** [comment]
The `sed` invocation is this: `sed -i -E 's|^(\s*resolved\s*")https?://.*/|\1|' yarn.lock`. Which means the `s` is optional in `https`. Not sure how this causes trouble for you since I'm using it with plain HTTP URLs successfully.
For `fetchgit`, maybe check out the https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchgit/default.nix#L14 `leaveDotGit` option. I'm not sure about the details anymore, but I'm sure this has an impact on the resulting hash.

**Comment by rimmington** [comment]
@manveru I'm using `git+ssh` urls, and I believe that a HTTP Git dependency is declared using `git+https`.

Regarding `fetchgit`/`nix-prefetch-git`, the actual content of the output is the same, but the store path is different (my previous comment was unclear).

**Comment by moretea** [comment]
@manveru @zimbatm maybe we could take a look at this tomorrow/Tuesday :)?

**Comment by betaboon** [comment]
Hello,

After running into problems like https://github.com/moretea/yarn2nix/issues/53 when trying to build an angular application i just had to figure this out.

i just tried this PR rebased onto current master and added the following changes to make my case work:

```diff
diff --git a/default.nix b/default.nix
index 8321435..503142c 100644
--- a/default.nix
+++ b/default.nix
@@ -4,7 +4,7 @@
 }:
 
 let
-  inherit (pkgs) stdenv lib fetchurl linkFarm;
+  inherit (pkgs) stdenv lib fetchurl fetchgit linkFarm;
 in rec {
   # Export yarn again to make it easier to find out which yarn was used.
   inherit yarn;
@@ -32,7 +32,7 @@ in rec {
   # the package source.
   importOfflineCache = yarnNix:
     let
-      pkg = import yarnNix { inherit fetchurl linkFarm; };
+      pkg = import yarnNix { inherit fetchurl linkFarm fetchgit; };
     in
       pkg.offline_cache;
 
@@ -86,10 +86,13 @@ in rec {
         chmod +w ./yarn.lock
 
         yarn config --offline set yarn-offline-mirror ${offlineCache}
+        yarn config --offline set yarn-offline-mirror-pruning false
 
         # Do not look up in the registry, but in the offline cache.
         # TODO: Ask upstream to fix this mess.
+        sed -i -E 's|^(\s*resolved\s*")https?://.*\/@([^/]*)\/.*\/(.*)|\1\2_\3|' yarn.lock
         sed -i -E 's|^(\s*resolved\s*")https?://.*/|\1|' yarn.lock
+
         yarn install ${lib.escapeShellArgs yarnFlags}
 
         ${lib.concatStringsSep "\n" postInstall}
diff --git a/yarn.nix b/yarn.nix
index a9e42e7..1ec3c13 100644
--- a/yarn.nix
+++ b/yarn.nix
@@ -1,9 +1,9 @@
-{fetchurl, linkFarm}: rec {
+{fetchurl, linkFarm, fetchgit}: rec {
   offline_cache = linkFarm "offline" packages;
   packages = [
 
     {
-      name = "lockfile-1.0.0.tgz";
+      name = "yarnpkg_lockfile-1.0.0.tgz";
       path = fetchurl {
         name = "lockfile-1.0.0.tgz";
         url  = "https://registry.yarnpkg.com/@yarnpkg/lockfile/-/lockfile-1.0.0.tgz";
```

**Comment by srghma** [comment]
@coltfred this feature is implemented https://github.com/moretea/yarn2nix/pull/92

**Pull request closed without merging**
